config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "samples#index"
  resources :samples ,only: :index
  get "samples/test"
  get "samples/samurai"
  
  get "forms/new"
  post "forms/create"
  
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/form.rb
class Form < ApplicationRecord
end

app/models/sample.rb
class Sample < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/forms_controller.rb
class FormsController < ApplicationController
    
    def new
        @form = Form.new
    end
    
    def create
      @form = Form.create(form_params)
    end
    
  private
    def form_params
        params.require(:form).permit(:name, :email, :phone, :content)
    end
    
end

app/controllers/samples_controller.rb
class SamplesController < ApplicationController
  before_action :set_sample, only: [:show, :edit, :update, :destroy]


  def index
  end
  
  def test
    
  end
  
  def samurai
  
  end
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  

  # GET /samples/1
  # GET /samples/1.json
  def show
  end

  # GET /samples/new
  def new
    @sample = Sample.new
  end

  # GET /samples/1/edit
  def edit
  end

  # POST /samples
  # POST /samples.json
  def create
    @sample = Sample.new(sample_params)

    respond_to do |format|
      if @sample.save
        format.html { redirect_to @sample, notice: 'Sample was successfully created.' }
        format.json { render :show, status: :created, location: @sample }
      else
        format.html { render :new }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /samples/1
  # PATCH/PUT /samples/1.json
  def update
    respond_to do |format|
      if @sample.update(sample_params)
        format.html { redirect_to @sample, notice: 'Sample was successfully updated.' }
        format.json { render :show, status: :ok, location: @sample }
      else
        format.html { render :edit }
        format.json { render json: @sample.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /samples/1
  # DELETE /samples/1.json
  def destroy
    @sample.destroy
    respond_to do |format|
      format.html { redirect_to samples_url, notice: 'Sample was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sample
      @sample = Sample.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sample_params
      params.fetch(:sample, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forms_helper.rb
module FormsHelper
end

app/helpers/samples_helper.rb
module SamplesHelper
end

app/views/forms/create.html.erb
<section id="services">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase"><%= @form.name%>様</h2>
            <h3 class="section-subheading text-muted">お問い合わせ有難うございます</h3>
          </div>
        </div>
      </div>
    </section>

app/views/forms/new.html.erb
    <!-- Contact -->
    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Contact Us</h2>
            <h3 class="section-subheading text-muted">お問合わせはこちらから</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            
            <!--form-->
            <%= form_for(@form, url: forms_create_path) do |f| %>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.text_field :name, class: 'form-control', placeholder: 'あなたのお名前 *', id: 'name'  %>
                  </div>
                  <div class="form-group">
                    <%= f.text_field :email, class: 'form-control', placeholder: 'メールアドレス *', id: 'email'  %>
                  </div>
                  <div class="form-group">
                    <%= f.text_field :phone, class: 'form-control', placeholder: '電話番号 *', id: 'phonel'  %>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <%= f.text_area :content, class: 'form-control', placeholder: 'お問い合わせ内容 *', id: 'message'%>
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <%= f.submit "メッセージを送信する", class:'btn btn-primary btn-xl text-uppercase'%>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BootSample</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/samples/_form.html.erb
<%= form_with(model: sample, local: true) do |form| %>
  <% if sample.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sample.errors.count, "error") %> prohibited this sample from being saved:</h2>

      <ul>
      <% sample.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/samples/edit.html.erb
<h1>Editing Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Show', @sample %> |
<%= link_to 'Back', samples_path %>

app/views/samples/new.html.erb
<h1>New Sample</h1>

<%= render 'form', sample: @sample %>

<%= link_to 'Back', samples_path %>

app/views/samples/samurai.html.erb
    <!-- Contact -->
    <section id="contact">
      <div class="container">
        <div class="row">
          <div class="col-lg-12 text-center">
            <h2 class="section-heading text-uppercase">Contact Us</h2>
            <h3 class="section-subheading text-muted">お問合わせはこちらから</h3>
          </div>
        </div>
        <div class="row">
          <div class="col-lg-12">
            
            <!--form-->
            <form id="contactForm" name="sentMessage" novalidate>
              <div class="row">
                <div class="col-md-6">
                  <div class="form-group">
                    <input class="form-control" id="name" type="text" placeholder="あなたのお名前 *" required data-validation-required-message="Please enter your name.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" id="email" type="email" placeholder="メールアドレス *" required data-validation-required-message="Please enter your email address.">
                    <p class="help-block text-danger"></p>
                  </div>
                  <div class="form-group">
                    <input class="form-control" id="phone" type="tel" placeholder="電話番号 *" required data-validation-required-message="Please enter your phone number.">
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="col-md-6">
                  <div class="form-group">
                    <textarea class="form-control" id="message" placeholder="お問い合わせ内容 *" required data-validation-required-message="Please enter a message."></textarea>
                    <p class="help-block text-danger"></p>
                  </div>
                </div>
                <div class="clearfix"></div>
                <div class="col-lg-12 text-center">
                  <div id="success"></div>
                  <button id="メッセージを送信する" class="btn btn-primary btn-xl text-uppercase" type="submit">メッセージを送信する</button>
                </div>
              </div>
            </form>
          </div>
        </div>
      </div>
    </section>

app/views/samples/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_sample_path(@sample) %> |
<%= link_to 'Back', samples_path %>

app/views/samples/test.html.erb
<p>こんにちは</p>